# Generated by Django 3.2.6 on 2021-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
